import { PlayerCompare } from "../dist/ai/gameperf.js";
import { AI, AIMode, AIOpts } from "../dist/ai/players.js";
const opts0 = new AIOpts();
opts0.timeout = 100;
opts0.mode = AIMode.TIME;
opts0.genBased = true;
opts0.pruning = 1 /* PruningType.ALPHA_BETA */;
opts0.clone = 0 /* CloneMethod.STANDARD */;
const player0 = new AI(0, opts0);
const opts1 = new AIOpts();
opts1.timeout = 100;
opts1.mode = AIMode.TIME;
opts1.genBased = true;
opts1.pruning = 1 /* PruningType.ALPHA_BETA */;
opts1.clone = 1 /* CloneMethod.SMART */;
const player1 = new AI(1, opts1);
const players = [player0, player1];
const pc = new PlayerCompare(players);
pc.compare_alternate();
